var searchData=
[
  ['tapachievementstarttask_2ecs_542',['TapAchievementStartTask.cs',['../_tap_achievement_start_task_8cs.html',1,'']]],
  ['tapbootstrap_2ecs_543',['TapBootstrap.cs',['../_tap_bootstrap_8cs.html',1,'']]],
  ['tapbootstrapimpl_2ecs_544',['TapBootstrapImpl.cs',['../_tap_bootstrap_impl_8cs.html',1,'']]],
  ['tapbootstrapsdk_2eassemblyinfo_2ecs_545',['TapBootstrapSDK.AssemblyInfo.cs',['../_debug_2netstandard2_80_2_tap_bootstrap_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_release_2netstandard2_80_2_tap_bootstrap_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)']]],
  ['tapbootstraptest_2eassemblyinfo_2ecs_546',['TapBootstrapTest.AssemblyInfo.cs',['../_tap_bootstrap_test_8_assembly_info_8cs.html',1,'']]],
  ['tapcommon_2ecs_547',['TapCommon.cs',['../_tap_common_8cs.html',1,'']]],
  ['tapcommonimpl_2ecs_548',['TapCommonImpl.cs',['../_tap_common_impl_8cs.html',1,'']]],
  ['tapcommonsdk_2eassemblyinfo_2ecs_549',['TapCommonSDK.AssemblyInfo.cs',['../_debug_2netstandard2_80_2_tap_common_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_i_o_s_2netstandard2_80_2_tap_common_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_release_2netstandard2_80_2_tap_common_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)']]],
  ['tapconfig_2ecs_550',['TapConfig.cs',['../_tap_config_8cs.html',1,'']]],
  ['tapdb_2ecs_551',['TapDB.cs',['../_tap_d_b_8cs.html',1,'']]],
  ['tapdbconstants_2ecs_552',['TapDBConstants.cs',['../_tap_d_b_constants_8cs.html',1,'']]],
  ['tapdbimpl_2ecs_553',['TapDBImpl.cs',['../_tap_d_b_impl_8cs.html',1,'']]],
  ['tapdblogintype_2ecs_554',['TapDBLoginType.cs',['../_tap_d_b_login_type_8cs.html',1,'']]],
  ['tapdbsdk_2eassemblyinfo_2ecs_555',['TapDBSDK.AssemblyInfo.cs',['../_release_2netstandard2_80_2_tap_d_b_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_debug_2netstandard2_80_2_tap_d_b_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_i_o_s_2netstandard2_80_2_tap_d_b_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)']]],
  ['tapdbstarttask_2ecs_556',['TapDBStartTask.cs',['../_tap_d_b_start_task_8cs.html',1,'']]],
  ['taperror_2ecs_557',['TapError.cs',['../_tap_common_s_d_k_2_tap_error_8cs.html',1,'(Global Namespace)'],['../_tap_friends_s_d_k_2_tap_error_8cs.html',1,'(Global Namespace)']]],
  ['taperrorcode_2ecs_558',['TapErrorCode.cs',['../_tap_common_s_d_k_2_tap_error_code_8cs.html',1,'(Global Namespace)'],['../_tap_friends_s_d_k_2_tap_error_code_8cs.html',1,'(Global Namespace)']]],
  ['tapexception_2ecs_559',['TapException.cs',['../_tap_exception_8cs.html',1,'']]],
  ['tapfriendrelationwrapper_2ecs_560',['TapFriendRelationWrapper.cs',['../_tap_friend_relation_wrapper_8cs.html',1,'']]],
  ['tapfriends_2ecs_561',['TapFriends.cs',['../_tap_friends_8cs.html',1,'']]],
  ['tapfriendsbridgewrapper_2ecs_562',['TapFriendsBridgeWrapper.cs',['../_tap_friends_bridge_wrapper_8cs.html',1,'']]],
  ['tapfriendsconstants_2ecs_563',['TapFriendsConstants.cs',['../_tap_friends_constants_8cs.html',1,'']]],
  ['tapfriendsimpl_2ecs_564',['TapFriendsImpl.cs',['../_tap_friends_impl_8cs.html',1,'']]],
  ['tapfriendssdk_2eassemblyinfo_2ecs_565',['TapFriendsSDK.AssemblyInfo.cs',['../_debug_2netstandard2_80_2_tap_friends_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_release_2netstandard2_80_2_tap_friends_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)']]],
  ['taplanguage_2ecs_566',['TapLanguage.cs',['../_tap_language_8cs.html',1,'']]],
  ['taplicense_2eassemblyinfo_2ecs_567',['TapLicense.AssemblyInfo.cs',['../_debug_2netstandard2_80_2_tap_license_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_release_2netstandard2_80_2_tap_license_8_assembly_info_8cs.html',1,'(Global Namespace)']]],
  ['taplicense_2ecs_568',['TapLicense.cs',['../_tap_license_8cs.html',1,'']]],
  ['taplicensecode_2ecs_569',['TapLicenseCode.cs',['../_tap_license_code_8cs.html',1,'']]],
  ['taplicenseimpl_2ecs_570',['TapLicenseImpl.cs',['../_tap_license_impl_8cs.html',1,'']]],
  ['taplogin_2ecs_571',['TapLogin.cs',['../_tap_login_8cs.html',1,'']]],
  ['taploginimpl_2ecs_572',['TapLoginImpl.cs',['../_tap_login_impl_8cs.html',1,'']]],
  ['taploginsdk_2eassemblyinfo_2ecs_573',['TapLoginSDK.AssemblyInfo.cs',['../_release_2netstandard2_80_2_tap_login_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_debug_2netstandard2_80_2_tap_login_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)']]],
  ['taploginwrapper_2ecs_574',['TapLoginWrapper.cs',['../_tap_login_wrapper_8cs.html',1,'']]],
  ['tapmoment_2ecs_575',['TapMoment.cs',['../_tap_moment_8cs.html',1,'']]],
  ['tapmomentimpl_2ecs_576',['TapMomentImpl.cs',['../_tap_moment_impl_8cs.html',1,'']]],
  ['tapmomentsdk_2eassemblyinfo_2ecs_577',['TapMomentSDK.AssemblyInfo.cs',['../_debug_2netstandard2_80_2_tap_moment_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_release_2netstandard2_80_2_tap_moment_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)']]],
  ['tapmomentstarttask_2ecs_578',['TapMomentStartTask.cs',['../_tap_moment_start_task_8cs.html',1,'']]],
  ['tapstarttaskholder_2ecs_579',['TapStartTaskHolder.cs',['../_tap_start_task_holder_8cs.html',1,'']]],
  ['tapstoragestarttask_2ecs_580',['TapStorageStartTask.cs',['../_tap_storage_start_task_8cs.html',1,'']]],
  ['taptaploginstarttask_2ecs_581',['TapTapLoginStartTask.cs',['../_tap_tap_login_start_task_8cs.html',1,'']]],
  ['tapuserrelationship_2ecs_582',['TapUserRelationShip.cs',['../_tap_user_relation_ship_8cs.html',1,'']]],
  ['tapuuid_2ecs_583',['TapUUID.cs',['../_tap_u_u_i_d_8cs.html',1,'']]],
  ['tdsuser_2ecs_584',['TDSUser.cs',['../_t_d_s_user_8cs.html',1,'']]]
];
