var searchData=
[
  ['tapachievement_2ecs_580',['TapAchievement.cs',['../_tap_achievement_8cs.html',1,'']]],
  ['tapachievementbean_2ecs_581',['TapAchievementBean.cs',['../_tap_achievement_bean_8cs.html',1,'']]],
  ['tapachievementimpl_2ecs_582',['TapAchievementImpl.cs',['../_tap_achievement_impl_8cs.html',1,'']]],
  ['tapachievementsdk_2eassemblyinfo_2ecs_583',['TapAchievementSDK.AssemblyInfo.cs',['../_debug_2netstandard2_80_2_tap_achievement_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_release_2netstandard2_80_2_tap_achievement_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)']]],
  ['tapachievementstarttask_2ecs_584',['TapAchievementStartTask.cs',['../_tap_achievement_start_task_8cs.html',1,'']]],
  ['tapbootstrap_2ecs_585',['TapBootstrap.cs',['../_tap_bootstrap_8cs.html',1,'']]],
  ['tapbootstrapimpl_2ecs_586',['TapBootstrapImpl.cs',['../_tap_bootstrap_impl_8cs.html',1,'']]],
  ['tapbootstrapsdk_2eassemblyinfo_2ecs_587',['TapBootstrapSDK.AssemblyInfo.cs',['../_debug_2netstandard2_80_2_tap_bootstrap_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_release_2netstandard2_80_2_tap_bootstrap_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)']]],
  ['tapcommon_2ecs_588',['TapCommon.cs',['../_tap_common_8cs.html',1,'']]],
  ['tapcommonimpl_2ecs_589',['TapCommonImpl.cs',['../_tap_common_impl_8cs.html',1,'']]],
  ['tapcommonsdk_2eassemblyinfo_2ecs_590',['TapCommonSDK.AssemblyInfo.cs',['../_debug_2netstandard2_80_2_tap_common_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_i_o_s_2netstandard2_80_2_tap_common_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_release_2netstandard2_80_2_tap_common_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)']]],
  ['tapcommonstarttask_2ecs_591',['TapCommonStartTask.cs',['../_tap_common_start_task_8cs.html',1,'']]],
  ['tapconfig_2ecs_592',['TapConfig.cs',['../_tap_config_8cs.html',1,'']]],
  ['tapdb_2ecs_593',['TapDB.cs',['../_tap_d_b_8cs.html',1,'']]],
  ['tapdbconstants_2ecs_594',['TapDBConstants.cs',['../_tap_d_b_constants_8cs.html',1,'']]],
  ['tapdbimpl_2ecs_595',['TapDBImpl.cs',['../_tap_d_b_impl_8cs.html',1,'']]],
  ['tapdblogintype_2ecs_596',['TapDBLoginType.cs',['../_tap_d_b_login_type_8cs.html',1,'']]],
  ['tapdbsdk_2eassemblyinfo_2ecs_597',['TapDBSDK.AssemblyInfo.cs',['../_release_2netstandard2_80_2_tap_d_b_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_i_o_s_2netstandard2_80_2_tap_d_b_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_debug_2netstandard2_80_2_tap_d_b_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)']]],
  ['tapdbstarttask_2ecs_598',['TapDBStartTask.cs',['../_tap_d_b_start_task_8cs.html',1,'']]],
  ['taperror_2ecs_599',['TapError.cs',['../_tap_error_8cs.html',1,'']]],
  ['taperrorcode_2ecs_600',['TapErrorCode.cs',['../_tap_error_code_8cs.html',1,'']]],
  ['tapexception_2ecs_601',['TapException.cs',['../_tap_exception_8cs.html',1,'']]],
  ['tapgamesave_2ecs_602',['TapGameSave.cs',['../_tap_game_save_8cs.html',1,'']]],
  ['taplanguage_2ecs_603',['TapLanguage.cs',['../_tap_language_8cs.html',1,'']]],
  ['taplicense_2eassemblyinfo_2ecs_604',['TapLicense.AssemblyInfo.cs',['../_debug_2netstandard2_80_2_tap_license_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_release_2netstandard2_80_2_tap_license_8_assembly_info_8cs.html',1,'(Global Namespace)']]],
  ['taplicense_2ecs_605',['TapLicense.cs',['../_tap_license_8cs.html',1,'']]],
  ['taplicensecode_2ecs_606',['TapLicenseCode.cs',['../_tap_license_code_8cs.html',1,'']]],
  ['taplicenseimpl_2ecs_607',['TapLicenseImpl.cs',['../_tap_license_impl_8cs.html',1,'']]],
  ['taplogin_2ecs_608',['TapLogin.cs',['../_tap_login_8cs.html',1,'']]],
  ['taploginimpl_2ecs_609',['TapLoginImpl.cs',['../_tap_login_impl_8cs.html',1,'']]],
  ['taploginsdk_2eassemblyinfo_2ecs_610',['TapLoginSDK.AssemblyInfo.cs',['../_debug_2netstandard2_80_2_tap_login_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_release_2netstandard2_80_2_tap_login_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)']]],
  ['taploginwrapper_2ecs_611',['TapLoginWrapper.cs',['../_tap_login_wrapper_8cs.html',1,'']]],
  ['tapmoment_2ecs_612',['TapMoment.cs',['../_tap_moment_8cs.html',1,'']]],
  ['tapmomentimpl_2ecs_613',['TapMomentImpl.cs',['../_tap_moment_impl_8cs.html',1,'']]],
  ['tapmomentsdk_2eassemblyinfo_2ecs_614',['TapMomentSDK.AssemblyInfo.cs',['../_debug_2netstandard2_80_2_tap_moment_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_release_2netstandard2_80_2_tap_moment_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)']]],
  ['tapmomentstarttask_2ecs_615',['TapMomentStartTask.cs',['../_tap_moment_start_task_8cs.html',1,'']]],
  ['tapstarttaskholder_2ecs_616',['TapStartTaskHolder.cs',['../_tap_start_task_holder_8cs.html',1,'']]],
  ['tapstoragestarttask_2ecs_617',['TapStorageStartTask.cs',['../_tap_storage_start_task_8cs.html',1,'']]],
  ['taptaploginstarttask_2ecs_618',['TapTapLoginStartTask.cs',['../_tap_tap_login_start_task_8cs.html',1,'']]],
  ['taptapsdk_2ecs_619',['TapTapSdk.cs',['../_tap_tap_sdk_8cs.html',1,'']]],
  ['tapuuid_2ecs_620',['TapUUID.cs',['../_tap_u_u_i_d_8cs.html',1,'']]],
  ['tdsuser_2ecs_621',['TDSUser.cs',['../_t_d_s_user_8cs.html',1,'']]]
];
