var searchData=
[
  ['tapbootstrap_2ecs_458',['TapBootstrap.cs',['../_tap_bootstrap_8cs.html',1,'']]],
  ['tapbootstrapconstants_2ecs_459',['TapBootstrapConstants.cs',['../_tap_bootstrap_constants_8cs.html',1,'']]],
  ['tapbootstrapimpl_2ecs_460',['TapBootstrapImpl.cs',['../_tap_bootstrap_impl_8cs.html',1,'']]],
  ['tapbootstrapsdk_2eassemblyinfo_2ecs_461',['TapBootstrapSDK.AssemblyInfo.cs',['../_tap_bootstrap_s_d_k_8_assembly_info_8cs.html',1,'']]],
  ['tapbridgewrapper_2ecs_462',['TapBridgeWrapper.cs',['../_tap_bridge_wrapper_8cs.html',1,'']]],
  ['tapcommon_2ecs_463',['TapCommon.cs',['../_tap_common_8cs.html',1,'']]],
  ['tapcommonimpl_2ecs_464',['TapCommonImpl.cs',['../_tap_common_impl_8cs.html',1,'']]],
  ['tapcommonsdk_2eassemblyinfo_2ecs_465',['TapCommonSDK.AssemblyInfo.cs',['../_release_2netstandard2_80_2_tap_common_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_i_o_s_2netstandard2_80_2_tap_common_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)']]],
  ['tapconfig_2ecs_466',['TapConfig.cs',['../_tap_config_8cs.html',1,'']]],
  ['tapdb_2ecs_467',['TapDB.cs',['../_tap_d_b_8cs.html',1,'']]],
  ['tapdbconstants_2ecs_468',['TapDBConstants.cs',['../_tap_d_b_constants_8cs.html',1,'']]],
  ['tapdbimpl_2ecs_469',['TapDBImpl.cs',['../_tap_d_b_impl_8cs.html',1,'']]],
  ['tapdblogintype_2ecs_470',['TapDBLoginType.cs',['../_tap_d_b_login_type_8cs.html',1,'']]],
  ['tapdbsdk_2eassemblyinfo_2ecs_471',['TapDBSDK.AssemblyInfo.cs',['../_i_o_s_2netstandard2_80_2_tap_d_b_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_debug_2netstandard2_80_2_tap_d_b_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_release_2netstandard2_80_2_tap_d_b_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)']]],
  ['taperror_2ecs_472',['TapError.cs',['../_tap_friends_s_d_k_2_tap_error_8cs.html',1,'(Global Namespace)'],['../_tap_bootstrap_s_d_k_2_tap_error_8cs.html',1,'(Global Namespace)']]],
  ['taperrorcode_2ecs_473',['TapErrorCode.cs',['../_tap_friends_s_d_k_2_tap_error_code_8cs.html',1,'(Global Namespace)'],['../_tap_bootstrap_s_d_k_2_tap_error_code_8cs.html',1,'(Global Namespace)']]],
  ['tapfriendrelationwrapper_2ecs_474',['TapFriendRelationWrapper.cs',['../_tap_friend_relation_wrapper_8cs.html',1,'']]],
  ['tapfriends_2ecs_475',['TapFriends.cs',['../_tap_friends_8cs.html',1,'']]],
  ['tapfriendsbridgewrapper_2ecs_476',['TapFriendsBridgeWrapper.cs',['../_tap_friends_bridge_wrapper_8cs.html',1,'']]],
  ['tapfriendsconstants_2ecs_477',['TapFriendsConstants.cs',['../_tap_friends_constants_8cs.html',1,'']]],
  ['tapfriendsimpl_2ecs_478',['TapFriendsImpl.cs',['../_tap_friends_impl_8cs.html',1,'']]],
  ['tapfriendssdk_2eassemblyinfo_2ecs_479',['TapFriendsSDK.AssemblyInfo.cs',['../_debug_2netstandard2_80_2_tap_friends_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_release_2netstandard2_80_2_tap_friends_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)']]],
  ['taplanguage_2ecs_480',['TapLanguage.cs',['../_tap_language_8cs.html',1,'']]],
  ['taplicense_2eassemblyinfo_2ecs_481',['TapLicense.AssemblyInfo.cs',['../_tap_license_8_assembly_info_8cs.html',1,'']]],
  ['taplicense_2ecs_482',['TapLicense.cs',['../_tap_license_8cs.html',1,'']]],
  ['taplicensecode_2ecs_483',['TapLicenseCode.cs',['../_tap_license_code_8cs.html',1,'']]],
  ['taplicenseimpl_2ecs_484',['TapLicenseImpl.cs',['../_tap_license_impl_8cs.html',1,'']]],
  ['taploginresultlistener_2ecs_485',['TapLoginResultListener.cs',['../_tap_login_result_listener_8cs.html',1,'']]],
  ['tapmoment_2ecs_486',['TapMoment.cs',['../_tap_moment_8cs.html',1,'']]],
  ['tapmomentimpl_2ecs_487',['TapMomentImpl.cs',['../_tap_moment_impl_8cs.html',1,'']]],
  ['tapmomentsdk_2eassemblyinfo_2ecs_488',['TapMomentSDK.AssemblyInfo.cs',['../_tap_moment_s_d_k_8_assembly_info_8cs.html',1,'']]],
  ['tapuser_2ecs_489',['TapUser.cs',['../_tap_user_8cs.html',1,'']]],
  ['tapuserdetail_2ecs_490',['TapUserDetail.cs',['../_tap_user_detail_8cs.html',1,'']]],
  ['tapuserrelationship_2ecs_491',['TapUserRelationShip.cs',['../_tap_user_relation_ship_8cs.html',1,'']]],
  ['tapuserstatuschangedlistener_2ecs_492',['TapUserStatusChangedListener.cs',['../_tap_user_status_changed_listener_8cs.html',1,'']]],
  ['tapuuid_2ecs_493',['TapUUID.cs',['../_tap_u_u_i_d_8cs.html',1,'']]]
];
