var searchData=
[
  ['tapbootstrap_2ecs_461',['TapBootstrap.cs',['../_tap_bootstrap_8cs.html',1,'']]],
  ['tapbootstrapimpl_2ecs_462',['TapBootstrapImpl.cs',['../_tap_bootstrap_impl_8cs.html',1,'']]],
  ['tapbootstrapsdk_2eassemblyinfo_2ecs_463',['TapBootstrapSDK.AssemblyInfo.cs',['../_debug_2netstandard2_80_2_tap_bootstrap_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_release_2netstandard2_80_2_tap_bootstrap_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)']]],
  ['tapcommon_2ecs_464',['TapCommon.cs',['../_tap_common_8cs.html',1,'']]],
  ['tapcommonimpl_2ecs_465',['TapCommonImpl.cs',['../_tap_common_impl_8cs.html',1,'']]],
  ['tapcommonsdk_2eassemblyinfo_2ecs_466',['TapCommonSDK.AssemblyInfo.cs',['../_debug_2netstandard2_80_2_tap_common_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_i_o_s_2netstandard2_80_2_tap_common_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_release_2netstandard2_80_2_tap_common_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)']]],
  ['tapconfig_2ecs_467',['TapConfig.cs',['../_tap_config_8cs.html',1,'']]],
  ['tapdb_2ecs_468',['TapDB.cs',['../_tap_d_b_8cs.html',1,'']]],
  ['tapdbconstants_2ecs_469',['TapDBConstants.cs',['../_tap_d_b_constants_8cs.html',1,'']]],
  ['tapdbimpl_2ecs_470',['TapDBImpl.cs',['../_tap_d_b_impl_8cs.html',1,'']]],
  ['tapdblogintype_2ecs_471',['TapDBLoginType.cs',['../_tap_d_b_login_type_8cs.html',1,'']]],
  ['tapdbsdk_2eassemblyinfo_2ecs_472',['TapDBSDK.AssemblyInfo.cs',['../_debug_2netstandard2_80_2_tap_d_b_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_i_o_s_2netstandard2_80_2_tap_d_b_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_release_2netstandard2_80_2_tap_d_b_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)']]],
  ['tapdbstarttask_2ecs_473',['TapDBStartTask.cs',['../_tap_d_b_start_task_8cs.html',1,'']]],
  ['taperror_2ecs_474',['TapError.cs',['../_tap_common_s_d_k_2_tap_error_8cs.html',1,'(Global Namespace)'],['../_tap_friends_s_d_k_2_tap_error_8cs.html',1,'(Global Namespace)']]],
  ['taperrorcode_2ecs_475',['TapErrorCode.cs',['../_tap_common_s_d_k_2_tap_error_code_8cs.html',1,'(Global Namespace)'],['../_tap_friends_s_d_k_2_tap_error_code_8cs.html',1,'(Global Namespace)']]],
  ['tapexception_2ecs_476',['TapException.cs',['../_tap_exception_8cs.html',1,'']]],
  ['tapfriendrelationwrapper_2ecs_477',['TapFriendRelationWrapper.cs',['../_tap_friend_relation_wrapper_8cs.html',1,'']]],
  ['tapfriends_2ecs_478',['TapFriends.cs',['../_tap_friends_8cs.html',1,'']]],
  ['tapfriendsbridgewrapper_2ecs_479',['TapFriendsBridgeWrapper.cs',['../_tap_friends_bridge_wrapper_8cs.html',1,'']]],
  ['tapfriendsconstants_2ecs_480',['TapFriendsConstants.cs',['../_tap_friends_constants_8cs.html',1,'']]],
  ['tapfriendsimpl_2ecs_481',['TapFriendsImpl.cs',['../_tap_friends_impl_8cs.html',1,'']]],
  ['tapfriendssdk_2eassemblyinfo_2ecs_482',['TapFriendsSDK.AssemblyInfo.cs',['../_release_2netstandard2_80_2_tap_friends_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_debug_2netstandard2_80_2_tap_friends_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)']]],
  ['taplanguage_2ecs_483',['TapLanguage.cs',['../_tap_language_8cs.html',1,'']]],
  ['taplicense_2eassemblyinfo_2ecs_484',['TapLicense.AssemblyInfo.cs',['../_release_2netstandard2_80_2_tap_license_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_debug_2netstandard2_80_2_tap_license_8_assembly_info_8cs.html',1,'(Global Namespace)']]],
  ['taplicense_2ecs_485',['TapLicense.cs',['../_tap_license_8cs.html',1,'']]],
  ['taplicensecode_2ecs_486',['TapLicenseCode.cs',['../_tap_license_code_8cs.html',1,'']]],
  ['taplicenseimpl_2ecs_487',['TapLicenseImpl.cs',['../_tap_license_impl_8cs.html',1,'']]],
  ['tapmoment_2ecs_488',['TapMoment.cs',['../_tap_moment_8cs.html',1,'']]],
  ['tapmomentimpl_2ecs_489',['TapMomentImpl.cs',['../_tap_moment_impl_8cs.html',1,'']]],
  ['tapmomentsdk_2eassemblyinfo_2ecs_490',['TapMomentSDK.AssemblyInfo.cs',['../_debug_2netstandard2_80_2_tap_moment_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_release_2netstandard2_80_2_tap_moment_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)']]],
  ['tapmomentstarttask_2ecs_491',['TapMomentStartTask.cs',['../_tap_moment_start_task_8cs.html',1,'']]],
  ['tapstarttaskholder_2ecs_492',['TapStartTaskHolder.cs',['../_tap_start_task_holder_8cs.html',1,'']]],
  ['tapstoragestarttask_2ecs_493',['TapStorageStartTask.cs',['../_tap_storage_start_task_8cs.html',1,'']]],
  ['taptaploginstarttask_2ecs_494',['TapTapLoginStartTask.cs',['../_tap_tap_login_start_task_8cs.html',1,'']]],
  ['tapuserrelationship_2ecs_495',['TapUserRelationShip.cs',['../_tap_user_relation_ship_8cs.html',1,'']]],
  ['tapuuid_2ecs_496',['TapUUID.cs',['../_tap_u_u_i_d_8cs.html',1,'']]],
  ['tdsuser_2ecs_497',['TDSUser.cs',['../_t_d_s_user_8cs.html',1,'']]]
];
