var searchData=
[
  ['tapachievement_2ecs_522',['TapAchievement.cs',['../_tap_achievement_8cs.html',1,'']]],
  ['tapachievementbean_2ecs_523',['TapAchievementBean.cs',['../_tap_achievement_bean_8cs.html',1,'']]],
  ['tapachievementimpl_2ecs_524',['TapAchievementImpl.cs',['../_tap_achievement_impl_8cs.html',1,'']]],
  ['tapachievementsdk_2eassemblyinfo_2ecs_525',['TapAchievementSDK.AssemblyInfo.cs',['../_debug_2netstandard2_80_2_tap_achievement_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_release_2netstandard2_80_2_tap_achievement_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)']]],
  ['tapachievementstarttask_2ecs_526',['TapAchievementStartTask.cs',['../_tap_achievement_start_task_8cs.html',1,'']]],
  ['tapbootstrap_2ecs_527',['TapBootstrap.cs',['../_tap_bootstrap_8cs.html',1,'']]],
  ['tapbootstrapimpl_2ecs_528',['TapBootstrapImpl.cs',['../_tap_bootstrap_impl_8cs.html',1,'']]],
  ['tapbootstrapsdk_2eassemblyinfo_2ecs_529',['TapBootstrapSDK.AssemblyInfo.cs',['../_debug_2netstandard2_80_2_tap_bootstrap_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_release_2netstandard2_80_2_tap_bootstrap_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)']]],
  ['tapcommon_2ecs_530',['TapCommon.cs',['../_tap_common_8cs.html',1,'']]],
  ['tapcommonimpl_2ecs_531',['TapCommonImpl.cs',['../_tap_common_impl_8cs.html',1,'']]],
  ['tapcommonsdk_2eassemblyinfo_2ecs_532',['TapCommonSDK.AssemblyInfo.cs',['../_debug_2netstandard2_80_2_tap_common_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_i_o_s_2netstandard2_80_2_tap_common_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_release_2netstandard2_80_2_tap_common_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)']]],
  ['tapconfig_2ecs_533',['TapConfig.cs',['../_tap_config_8cs.html',1,'']]],
  ['tapdb_2ecs_534',['TapDB.cs',['../_tap_d_b_8cs.html',1,'']]],
  ['tapdbconstants_2ecs_535',['TapDBConstants.cs',['../_tap_d_b_constants_8cs.html',1,'']]],
  ['tapdbimpl_2ecs_536',['TapDBImpl.cs',['../_tap_d_b_impl_8cs.html',1,'']]],
  ['tapdblogintype_2ecs_537',['TapDBLoginType.cs',['../_tap_d_b_login_type_8cs.html',1,'']]],
  ['tapdbsdk_2eassemblyinfo_2ecs_538',['TapDBSDK.AssemblyInfo.cs',['../_release_2netstandard2_80_2_tap_d_b_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_i_o_s_2netstandard2_80_2_tap_d_b_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_debug_2netstandard2_80_2_tap_d_b_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)']]],
  ['tapdbstarttask_2ecs_539',['TapDBStartTask.cs',['../_tap_d_b_start_task_8cs.html',1,'']]],
  ['taperror_2ecs_540',['TapError.cs',['../_tap_error_8cs.html',1,'']]],
  ['taperrorcode_2ecs_541',['TapErrorCode.cs',['../_tap_error_code_8cs.html',1,'']]],
  ['tapexception_2ecs_542',['TapException.cs',['../_tap_exception_8cs.html',1,'']]],
  ['taplanguage_2ecs_543',['TapLanguage.cs',['../_tap_language_8cs.html',1,'']]],
  ['taplicense_2eassemblyinfo_2ecs_544',['TapLicense.AssemblyInfo.cs',['../_debug_2netstandard2_80_2_tap_license_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_release_2netstandard2_80_2_tap_license_8_assembly_info_8cs.html',1,'(Global Namespace)']]],
  ['taplicense_2ecs_545',['TapLicense.cs',['../_tap_license_8cs.html',1,'']]],
  ['taplicensecode_2ecs_546',['TapLicenseCode.cs',['../_tap_license_code_8cs.html',1,'']]],
  ['taplicenseimpl_2ecs_547',['TapLicenseImpl.cs',['../_tap_license_impl_8cs.html',1,'']]],
  ['taplogin_2ecs_548',['TapLogin.cs',['../_tap_login_8cs.html',1,'']]],
  ['taploginimpl_2ecs_549',['TapLoginImpl.cs',['../_tap_login_impl_8cs.html',1,'']]],
  ['taploginsdk_2eassemblyinfo_2ecs_550',['TapLoginSDK.AssemblyInfo.cs',['../_debug_2netstandard2_80_2_tap_login_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_release_2netstandard2_80_2_tap_login_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)']]],
  ['taploginwrapper_2ecs_551',['TapLoginWrapper.cs',['../_tap_login_wrapper_8cs.html',1,'']]],
  ['tapmoment_2ecs_552',['TapMoment.cs',['../_tap_moment_8cs.html',1,'']]],
  ['tapmomentimpl_2ecs_553',['TapMomentImpl.cs',['../_tap_moment_impl_8cs.html',1,'']]],
  ['tapmomentsdk_2eassemblyinfo_2ecs_554',['TapMomentSDK.AssemblyInfo.cs',['../_debug_2netstandard2_80_2_tap_moment_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_release_2netstandard2_80_2_tap_moment_s_d_k_8_assembly_info_8cs.html',1,'(Global Namespace)']]],
  ['tapmomentstarttask_2ecs_555',['TapMomentStartTask.cs',['../_tap_moment_start_task_8cs.html',1,'']]],
  ['tapstarttaskholder_2ecs_556',['TapStartTaskHolder.cs',['../_tap_start_task_holder_8cs.html',1,'']]],
  ['tapstoragestarttask_2ecs_557',['TapStorageStartTask.cs',['../_tap_storage_start_task_8cs.html',1,'']]],
  ['taptaploginstarttask_2ecs_558',['TapTapLoginStartTask.cs',['../_tap_tap_login_start_task_8cs.html',1,'']]],
  ['tapuuid_2ecs_559',['TapUUID.cs',['../_tap_u_u_i_d_8cs.html',1,'']]],
  ['tdsuser_2ecs_560',['TDSUser.cs',['../_t_d_s_user_8cs.html',1,'']]]
];
